export default {
  OBJETIVO: [
    "Recuperar um Artefato Perdido: Os jogadores devem encontrar e recuperar um artefato mágico poderoso que foi roubado ou perdido em algum lugar perigoso do mundo.",
    "Salvar uma Cidade Ameaçada: Uma cidade está sob a ameaça iminente de um exército de criaturas monstruosas ou uma força maligna, e os jogadores devem defender a cidade ou evacuar os cidadãos.",
    "Derrotar um Vilão Maléfico: Os jogadores são convocados para derrotar um vilão maléfico que está ameaçando a paz do reino, seja um feiticeiro maligno ou um governante tirano.",
    "Descobrir um Segredo Antigo: Uma pista misteriosa leva os jogadores a desvendar um segredo antigo escondido há séculos, relacionado a uma civilização perdida ou a um conhecimento proibido.",
    "Proteger um Emissário Real: Os jogadores são designados para proteger um emissário real em uma viagem perigosa através de territórios hostis, com intrigas políticas e emboscadas.",
    "Resolver uma Maldição: Uma maldição assola uma cidade ou um grupo de pessoas, e os jogadores devem descobrir sua origem e encontrar uma maneira de quebrá-la.",
    "Aprender uma Habilidade Rara: Os personagens buscam um mestre lendário para aprender uma habilidade ou magia rara que os ajudará a enfrentar futuros desafios.",
    "Resgatar Reféns: Os jogadores devem resgatar reféns mantidos por bandidos, sequestradores ou cultistas, desvendando pistas para sua localização.",
    "Explorar um Local Místico: Os personagens são encarregados de explorar um local místico, como uma floresta encantada, uma tumba ancestral ou um labirinto subterrâneo.",
    "Impedir um Ritual Obscuro: Uma seita está prestes a realizar um ritual obscuro que trará desgraça ao mundo, e os jogadores devem impedi-los antes que seja tarde demais.",
    "Procurar um Ente Querido Desaparecido: Um ente querido de um dos personagens desapareceu misteriosamente, e os jogadores embarcam em uma jornada para encontrá-lo.",
    "Negociar uma Paz Delicada: Os personagens são enviados como embaixadores para negociar a paz entre duas facções rivais, enfrentando desconfiança e conspirações.",
  ],
  GANCHO: [
    "A Carta Misteriosa: Os jogadores recebem uma carta selada com um emblema desconhecido, contendo um pedido de ajuda de um remetente desconhecido. A carta sugere um local e uma hora para um encontro.",
    "O Mapa Enigmático: Os personagens encontram um mapa antigo que parece levar a um local lendário cheio de tesouros ou poder. O mapa está incompleto, e eles devem encontrar as peças faltantes.",
    "O Desaparecimento de um Mentor: O mentor ou figura paterna/materna de um dos personagens desaparece misteriosamente, deixando para trás pistas enigmáticas sobre seu paradeiro.",
    "A Amaldiçoada Relíquia: Os jogadores adquirem uma relíquia supostamente poderosa, apenas para descobrir que ela está amaldiçoada. Agora, eles devem encontrar uma maneira de quebrar a maldição.",
    "A Noite das Estrelas Cadentes: Durante uma noite especial de estrelas cadentes, os personagens testemunham algo fora do comum nos céus e recebem visões misteriosas que os levam a uma jornada.",
    "O Pedido do Fantasma: Um fantasma assombrado aparece para os jogadores, implorando por ajuda para resolver seu assassinato ou cumprir uma promessa não cumprida em vida.",
    "O Torneio Épico: Uma competição lendária está sendo realizada na cidade, atraindo heróis de todos os cantos. Os personagens decidem competir para fama, fortuna ou honra.",
    "O Roubo da Joia da Coroa: A joia mais valiosa da coroa real foi roubada, e os personagens são contratados para rastrear o ladrão e recuperá-la antes que a notícia do roubo cause uma crise.",
    "O Pacto Antigo: Os jogadores descobrem um pacto antigo que pode ameaçar o mundo se não for quebrado ou cumprido. Agora, eles devem tomar uma decisão crucial.",
    "O Chamado da Natureza: Uma dríade ou espírito da natureza aparece para os personagens, alertando sobre uma ameaça iminente à floresta ou ao equilíbrio natural.",
    "A Profecia Sombria: Uma profecia antiga prevê um evento catastrófico que está prestes a acontecer, e os personagens são os únicos que podem impedir que isso se realize.",
    "A Busca pelo Conhecimento Perdido: Uma biblioteca secreta ou um sábio hermético possui um conhecimento vital, mas seu paradeiro é desconhecido. Os personagens devem encontrá-lo.",
  ],
  NPC: [
    "Rei ou Rainha Justa: Um governante sábio e benevolente que busca orientação dos heróis para resolver problemas em seu reino.",
    "Mago Enigmático: Um mago poderoso que detém conhecimento sobre magia antiga e pode treinar os personagens em troca de favores.",
    "Mercador Astuto: Um comerciante ambicioso que pode oferecer informações valiosas em troca de escolta ou ajuda para proteger suas mercadorias.",
    "Cavaleiro Honrado: Um cavaleiro lendário conhecido por sua honra e lealdade, disposto a auxiliar os personagens em sua busca.",
    "Ladino Charmoso: Um ladrão habilidoso com uma inclinação para trapaças e segredos, que pode se tornar um aliado ou um obstáculo.",
    "Oráculo Enigmático: Um vidente que pode prever eventos futuros, mas suas visões são enigmáticas e precisam ser decifradas.",
    "Xamã Tribal: Um líder espiritual de uma tribo que pode conceder bênçãos ou tarefas místicas aos personagens.",
    "Mestre da Guilda: O líder de uma guilda de aventureiros, que fornece missões e contratos aos personagens em troca de uma parte dos tesouros encontrados.",
    "Alquimista Louco: Um alquimista excêntrico com experimentos bizarros, que pode oferecer poções úteis ou tóxicas.",
    "Cauteloso Guardião de Tesouros: O guardião de um tesouro lendário que protege seu precioso conteúdo com armadilhas e enigmas.",
    "Necromante Obscuro: Um praticante das artes necromânticas que pode ser uma ameaça para o mundo ou um aliado em busca de redenção.",
    "Arqueiro Elfo: Um habilidoso arqueiro elfo com conhecimento de segredos antigos da floresta.",
    "Druida Ancião: Um druida experiente que protege a natureza com magias e sabedoria ancestral.",
    "Guerreiro Bárbaro: Um bárbaro feroz das terras selvagens, que pode ser um adversário formidável ou um aliado inesperado.",
    "Bardo Encantador: Um bardo talentoso que usa músicas e histórias para influenciar a realidade ao seu redor.",
  ],
  CENARIO: [
    "Castelo Assombrado: Os jogadores são convocados para investigar um castelo antigo que está supostamente assombrado por espíritos malignos. Eles devem desvendar os mistérios do castelo e descobrir a verdade por trás das aparições fantasmagóricas.",
    "Cidade Portuária: Uma cidade portuária movimentada cheia de comerciantes, piratas e segredos. Os personagens podem se envolver em atividades comerciais, intrigas políticas ou até mesmo enfrentar ataques de piratas.",
    "Floresta Encantada: Uma floresta mágica cheia de criaturas místicas, onde os jogadores podem encontrar dríades, fadas, e talvez até mesmo uma árvore antiga que concede desejos.",
    "Masmorra Perdida: Uma masmorra esquecida nas profundezas de uma montanha, cheia de armadilhas mortais, monstros e tesouros há muito perdidos.",
    "Aldeia Isolada: Uma aldeia isolada nas montanhas, cercada por nevascas constantes e ameaças de bestas das profundezas da terra. Os personagens devem ajudar a aldeia a sobreviver.",
    "Cidade Subterrânea: Uma cidade subterrânea construída por uma raça antiga, agora abandonada. Os jogadores podem explorar seus corredores sombrios e enfrentar os perigos que lá residem.",
    "Deserto Inóspito: Um deserto vasto e mortal, onde os personagens devem lidar com a escassez de água, tribos nômades, e as ruínas de uma civilização perdida.",
    "Reino das Nuvens: Uma cidade flutuante nas nuvens, onde a magia é abundante e as regras da física são desafiadas. Os personagens podem participar de intrigas nas alturas.",
    "Templo Submerso: Um templo antigo que está parcialmente submerso nas profundezas de um lago misterioso. Os personagens devem mergulhar em águas perigosas para desvendar seus segredos.",
    "Vale Encantado: Um vale escondido entre montanhas, onde a vegetação é exuberante, mas o equilíbrio da natureza está ameaçado por forças sombrias.",
    "Cidade de Ladrões: Uma cidade controlada por guildas de ladrões, onde os personagens podem se tornar heróis ou cair nas artimanhas dos criminosos.",
    "Cemitério Amaldiçoado: Um cemitério onde os mortos não descansam em paz e os personagens devem enfrentar horrores não naturais.",
  ],
  DESAFIO: [
    "Combate com Monstros: Encontro com um dragão feroz, trolls famintos por carne ou uma horda de mortos-vivos.",
    "Armadilhas Mortais: Os personagens devem desarmar ou evitar armadilhas engenhosas, como alçapões, dardos envenenados ou pisos escorregadios.",
    "Puzzles e Quebra-Cabeças:Resolução de enigmas mágicos, como quebra-cabeças de lógica, sequências de símbolos ou alavancas misteriosas.",
    "Intrigas Políticas:Confrontos com nobres manipuladores, conspirações políticas e dilemas éticos em uma corte real.",
    "Corrida contra o Tempo:Os personagens têm um prazo para encontrar uma cura, desativar uma bomba mágica ou impedir uma invasão iminente.",
    "Desafios de Habilidades:Testes de habilidades individuais, como escalada de penhascos, navegação em florestas densas ou negociações diplomáticas delicadas.",
    "Encontros Sociais:Interações com personagens não-jogadores carismáticos, onde o que é dito pode ser tão importante quanto as espadas empunhadas.",
    "Maldição ou Doença:Um personagem é amaldiçoado ou fica doente, e os outros devem encontrar uma maneira de curá-lo ou quebrar a maldição.",
    "Perseguição:Os personagens são perseguidos por inimigos implacáveis, seja em uma fuga frenética ou em uma busca para alcançar um objetivo antes dos adversários.",
    "Teste de Lealdade:Um membro do grupo é questionado sobre sua lealdade e os outros devem decidir se podem confiar nele.",
    "Eventos Naturais Extremos:Os personagens enfrentam tempestades furiosas, terremotos ou outros desastres naturais enquanto tentam completar uma missão.",
    "Batalha Épica:Uma grande batalha contra um exército inimigo, onde os personagens desempenham um papel crucial na vitória ou derrota.",
    "Caça ao Tesouro:Os personagens devem seguir uma série de pistas e resolver enigmas para encontrar um tesouro escondido.",
    "Encontro com um Antagonista Recorrente:Um antagonista que os personagens enfrentaram no passado reaparece para se vingar ou criar mais complicações.",
    "Escolhas Morais Difíceis:Os personagens são confrontados com dilemas éticos onde suas escolhas afetam o mundo ao seu redor.",
  ],
  REVIRAVOLTA: [
    "Traição de um Aliado: Um personagem que parecia ser um aliado leal revela-se um traidor, trabalhando secretamente contra o grupo.",
    "Identidade Revelada: Um NPC importante, como um mentor ou um líder de guilda, revela uma identidade surpreendente ou um segredo obscuro.",
    "Arma Poderosa Corrompida: Uma arma mágica que os personagens encontraram e confiaram revela-se corrupta, tornando-se uma ameaça para eles.",
    "Aliados Perdidos: Os personagens encontram aliados de aventuras anteriores que se perderam ou mudaram de lado, criando tensões e dilemas morais.",
    "Objetivo Realocado: O objetivo original da aventura é desviado para algo completamente inesperado, levando os personagens a uma missão totalmente diferente.",
    "Mistério dos Gêmeos: Um NPC aparentemente único é, na verdade, um dos gêmeos de um par idêntico, e o outro gêmeo tem intenções e identidade distintas.",
    "Revelação de um Duplo Agente: Um membro do grupo é revelado como um agente infiltrado de uma facção inimiga, desencadeando uma crise interna.",
    "Vítima Inesperada: Um NPC aparentemente insignificante ou vítima de algum evento se revela fundamental para o enredo e possui habilidades ou conhecimentos ocultos.",
    "Inimigo Transformado: Um inimigo implacável se transforma em aliado ou busca a redenção, mudando a dinâmica da história.",
    "Falsa Pista: Uma pista aparentemente crucial leva os personagens a um beco sem saída, forçando-os a repensar suas investigações.",
    "Revelação de um Propósito Oculto: Um objeto ou local que parecia sem importância revela-se fundamental para o sucesso da missão.",
    "Identidade Enganosa: Um NPC que os personagens acreditavam ser alguém é, na verdade, uma ilusão ou um disfarce.",
    "Trama de Família: Um personagem descobre ter uma conexão familiar surpreendente com um NPC ou inimigo.",
    "Passagem para Outro Mundo: Os personagens encontram um portal mágico que os leva a um reino paralelo ou dimensão alternativa.",
    "Aparição Inesperada: Um personagem que se acreditava morto ou desaparecido aparece inesperadamente para ajudar ou prejudicar os jogadores.",
  ],
  RECOMPENSA: [
    "Tesouros: Moedas de ouro, joias preciosas, itens mágicos ou artefatos antigos que aumentam o poder ou habilidades dos personagens.",
    "Experiência: Pontos de experiência que permitem que os personagens subam de nível e desbloqueiem novas habilidades.",
    "Conhecimento: Informações valiosas, segredos ou mapas que ajudam os personagens em futuras aventuras.",
    "Aliados: NPCs que se tornam aliados confiáveis e podem ajudar os personagens com informações, habilidades especiais ou suporte em combate.",
    "Fama e Reconhecimento: Os personagens ganham reconhecimento e respeito em sua comunidade ou no mundo, o que pode abrir portas e oportunidades.",
    "Terras ou Propriedades: Os personagens recebem terras, propriedades ou uma base segura para descansar e planejar suas futuras aventuras.",
    "Itens Mágicos: Poções, pergaminhos, armas ou armaduras mágicas que concedem poderes especiais.",
    "Recompensas Monetárias Recorrentes: Os personagens recebem um salário ou pagamento regular por serviços prestados, como guardas de uma cidade.",
    "Bênçãos ou Dádivas Divinas: Poderes ou bênçãos concedidos por uma divindade, como habilidades divinas ou proteção contra o mal.",
    "Seguidores ou Servos: Os personagens ganham seguidores leais ou servos que os ajudam em tarefas ou missões.",
    "Aprimoramento de Habilidades: Treinamento especializado que aumenta as habilidades dos personagens em áreas específicas, como magia, combate ou furtividade.",
    "Territórios Controlados: Os personagens obtêm controle sobre um território, cidade ou fortaleza que podem governar e coletar impostos.",
    "Restauração de Honra: Os personagens têm sua honra restaurada em uma comunidade após uma injustiça anterior.",
    "Cura ou Remoção de Maldição: Os personagens recebem cura para ferimentos graves ou a remoção de maldições que os afetam.",
    "Revelações de Enredo: Informações importantes sobre a história ou enredo geral da campanha.",
  ],
  LOCAL: [
    "Cidade Costeira Movimentada: Uma cidade portuária cheia de tavernas, mercadores e personagens variados, com o som das ondas ao fundo.",
    "Floresta Encantada: Uma floresta densa e mágica, onde árvores caminham e criaturas místicas espreitam.",
    "Montanhas Inexploradas: Um imponente conjunto de montanhas que esconde passagens secretas, cavernas e talvez até um dragão adormecido.",
    "Tumba Antiga: Uma tumba subterrânea repleta de armadilhas, múmias e enigmas para desafiar os personagens.",
    "Torre do Mago: Uma torre alta e sinistra onde um mago poderoso reside, cheia de experimentos e criaturas mágicas.",
    "Aldeia Isolada: Uma aldeia remota nas montanhas ou em uma floresta, com uma comunidade que mantém tradições únicas.",
    "Caverna Abandonada: Uma caverna esquecida, lar de goblins, trolls ou outras criaturas, repleta de tesouros escondidos.",
    "Cidade Flutuante: Uma cidade suspensa nas nuvens, acessível apenas por escadas mágicas ou criaturas voadoras.",
    "Templo Subaquático: Um templo antigo nas profundezas de um lago, cheio de estátuas submersas e corredores inundados.",
    "Planície Maldita: Uma vasta planície amaldiçoada, onde criaturas aberrantes e tempestades mágicas ameaçam os viajantes.",
    "Cemitério Assombrado: Um cemitério onde os mortos não descansam em paz, com túmulos profanados e espíritos errantes.",
    "Cidade de Pedra: Uma cidade construída em penhascos íngremes ou cavernas, com casas esculpidas na rocha.",
    "Ruínas de uma Civilização Antiga: As ruínas de uma civilização há muito desaparecida, com artefatos e inscrições antigas.",
    "Selva Mística: Uma selva densa e exuberante, onde plantas carnívoras, tribos indígenas e animais exóticos coexistem.",
    "Fortaleza Assediada: Uma fortaleza sob cerco de inimigos, com batalhas épicas e oportunidades para táticas de cerco.",
  ],
  TEMA: [
    "Alta Fantasia Épica: Uma narrativa grandiosa, com heróis enfrentando ameaças épicas e salvando o mundo de uma destruição iminente.",
    "Intriga Política: Foco em conspirações, jogos de poder e rivalidades em uma corte real ou cidade cheia de facções políticas.",
    "Horror Gótico: Uma atmosfera sombria, com elementos de terror, como castelos assombrados, criaturas monstruosas e segredos macabros.",
    "Busca Pessoal: A história se concentra nas jornadas e crescimento dos personagens, com desafios que testam sua moralidade e convicções.",
    "Mitologia e Deuses: Os deuses e a mitologia desempenham um papel central na história, com conflitos divinos e profecias a serem cumpridas.",
    "Mundo Pós-Apocalíptico: Um mundo devastado por catástrofes mágicas ou naturais, onde os personagens lutam pela sobrevivência.",
    "Caça a Monstros: Os personagens assumem o papel de caçadores de monstros, enfrentando ameaças sobrenaturais em missões perigosas.",
    "Viagem no Tempo: Uma narrativa que envolve viagens no tempo, onde os personagens exploram diferentes eras e enfrentam paradoxos temporais.",
  ],
  ATMOSFERA: [
    "Sombria e Sinistra: Uma atmosfera carregada de mistério e perigo, com cenários escuros e ameaças ocultas.",
    "Épica e Heróica: Uma atmosfera inspiradora e grandiosa, onde os personagens são heróis lendários em uma jornada épica.",
    "Misteriosa e Intrigante: Uma atmosfera cheia de enigmas e segredos a serem descobertos, mantendo os jogadores curiosos.",
    "Aventura e Exploração: Uma atmosfera de descoberta constante, com locais exóticos para explorar e desafios a superar.",
    "Assustadora e Claustrofóbica: Uma atmosfera de terror, onde os personagens se sentem constantemente ameaçados e encurralados.",
    "Fantasia Colorida: Uma atmosfera vibrante e cheia de cores, com paisagens exuberantes e criaturas mágicas.",
    "Melancólica e Nostálgica: Uma atmosfera que evoca emoções profundas, com personagens lidando com perdas e lembranças do passado.",
    "Alegre e Descontraída: Uma atmosfera leve e humorística, onde o foco está em situações cômicas e interações divertidas.",
  ],
};
